using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql;
using TexTrack.Web.Data;
using Xunit;

namespace TexTrack.Web.IntegrationTests;

public sealed class MigrationChainTests
{
    [Fact]
    public async Task Negative_stock_policy_migration_preserves_existing_stock_companies_and_blocks_empty_companies()
    {
        var sourceConnection = TestDatabaseSettings.GetConnectionString();
        var adminBuilder = new NpgsqlConnectionStringBuilder(sourceConnection) { SearchPath = string.Empty };
        var schema = $"negative_policy_migration_{Guid.NewGuid():N}";

        await using var admin = new NpgsqlConnection(adminBuilder.ConnectionString);
        await admin.OpenAsync();
        await using (var create = new NpgsqlCommand($"CREATE SCHEMA \"{schema}\"", admin))
            await create.ExecuteNonQueryAsync();

        try
        {
            var testBuilder = new NpgsqlConnectionStringBuilder(adminBuilder.ConnectionString) { SearchPath = schema };
            await using var connection = new NpgsqlConnection(testBuilder.ConnectionString);
            await connection.OpenAsync();
            await using (var fixture = new NpgsqlCommand("""
                CREATE TABLE companies
                (
                    id bigint PRIMARY KEY
                );
                CREATE TABLE stock_movements
                (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    company_id bigint NOT NULL
                );
                CREATE TABLE audit_logs
                (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    company_id bigint NOT NULL,
                    entity_type varchar(100) NOT NULL,
                    entity_id bigint,
                    action varchar(50) NOT NULL,
                    success boolean NOT NULL,
                    description varchar(1000) NOT NULL,
                    performed_by varchar(100) NOT NULL,
                    performed_at_utc timestamp with time zone NOT NULL
                );
                INSERT INTO companies(id) VALUES (1), (2);
                INSERT INTO stock_movements(company_id) VALUES (1);
                """, connection))
            {
                await fixture.ExecuteNonQueryAsync();
            }

            var migrationPath = Path.Combine(
                AppContext.BaseDirectory, "Data", "Migrations", "041_negative_stock_policy.sql");
            await using (var migrate = new NpgsqlCommand(await File.ReadAllTextAsync(migrationPath), connection))
                await migrate.ExecuteNonQueryAsync();

            await using var verify = new NpgsqlCommand("""
                SELECT
                    (SELECT allow_negative_stock FROM companies WHERE id = 1),
                    (SELECT allow_negative_stock FROM companies WHERE id = 2),
                    (SELECT COUNT(*) FROM audit_logs WHERE entity_type = 'CompanyInventoryPolicy'),
                    (SELECT COUNT(*) FROM audit_logs WHERE company_id = 1 AND description LIKE '%preserved Allow Negative Stock%'),
                    (SELECT COUNT(*) FROM audit_logs WHERE company_id = 2 AND description LIKE '%enabled Block Negative Stock%')
                """, connection);
            await using var reader = await verify.ExecuteReaderAsync();
            Assert.True(await reader.ReadAsync());
            Assert.True(reader.GetBoolean(0));
            Assert.False(reader.GetBoolean(1));
            Assert.Equal(2L, reader.GetInt64(2));
            Assert.Equal(1L, reader.GetInt64(3));
            Assert.Equal(1L, reader.GetInt64(4));
        }
        finally
        {
            await using var drop = new NpgsqlCommand($"DROP SCHEMA IF EXISTS \"{schema}\" CASCADE", admin);
            await drop.ExecuteNonQueryAsync();
        }
    }

    [Fact]
    public async Task Complete_sql_migration_chain_builds_job_work_order_process_schema_from_empty_database()
    {
        var sourceConnection = TestDatabaseSettings.GetConnectionString();
        var adminBuilder = new NpgsqlConnectionStringBuilder(sourceConnection) { SearchPath = string.Empty };
        var schema = $"migration_chain_{Guid.NewGuid():N}";

        await using var admin = new NpgsqlConnection(adminBuilder.ConnectionString);
        await admin.OpenAsync();
        await using (var create = new NpgsqlCommand($"CREATE SCHEMA \"{schema}\"", admin))
            await create.ExecuteNonQueryAsync();

        try
        {
            var testBuilder = new NpgsqlConnectionStringBuilder(adminBuilder.ConnectionString) { SearchPath = schema };
            await using var connection = new NpgsqlConnection(testBuilder.ConnectionString);
            await connection.OpenAsync();

            var migrationsDirectory = Path.Combine(AppContext.BaseDirectory, "Data", "Migrations");
            var migrations = Directory.GetFiles(migrationsDirectory, "*.sql")
                .OrderBy(Path.GetFileName, StringComparer.Ordinal)
                .ToArray();

            Assert.Equal(42, migrations.Length);
            for (var expectedVersion = 1; expectedVersion <= migrations.Length; expectedVersion++)
            {
                Assert.StartsWith($"{expectedVersion:000}_", Path.GetFileName(migrations[expectedVersion - 1]));
                var sql = await File.ReadAllTextAsync(migrations[expectedVersion - 1]);
                await using var command = new NpgsqlCommand(sql, connection) { CommandTimeout = 120 };
                await command.ExecuteNonQueryAsync();
            }

            await using var verify = new NpgsqlCommand("""
                SELECT
                    to_regclass(current_schema() || '.job_work_order_processes') IS NOT NULL,
                    to_regclass(current_schema() || '.master_job_order_finished_goods') IS NOT NULL,
                    to_regclass(current_schema() || '.master_job_order_allocations') IS NOT NULL,
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'vouchers'
                          AND column_name = 'master_job_order_id'
                    ),
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'job_work_order_finished_goods'
                          AND column_name = 'design_group_key'
                    ),
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'job_work_order_size_allocations'
                          AND column_name = 'master_job_order_allocation_id'
                    ),
                    to_regclass(current_schema() || '.tally_company_links') IS NOT NULL,
                    to_regclass(current_schema() || '.tally_exchange_batches') IS NOT NULL,
                    to_regclass(current_schema() || '.tally_sync_records') IS NOT NULL,
                    to_regclass(current_schema() || '.tally_import_exceptions') IS NOT NULL,
                    to_regclass(current_schema() || '.tally_variant_allocation_tasks') IS NOT NULL,
                    to_regclass(current_schema() || '.bill_of_materials') IS NOT NULL,
                    to_regclass(current_schema() || '.bill_of_material_lines') IS NOT NULL,
                    to_regclass(current_schema() || '.job_work_order_bom_stages') IS NOT NULL
                    , EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'material_out_lines'
                          AND column_name = 'bom_stage_id'
                    ),
                    to_regclass(current_schema() || '.stock_item_field_definitions') IS NOT NULL,
                    to_regclass(current_schema() || '.stock_item_field_values') IS NOT NULL,
                    to_regclass(current_schema() || '.stock_item_photos') IS NOT NULL,
                    to_regclass(current_schema() || '.application_users') IS NOT NULL,
                    to_regclass(current_schema() || '.security_roles') IS NOT NULL,
                    to_regclass(current_schema() || '.application_user_roles') IS NOT NULL,
                    to_regclass(current_schema() || '.application_user_companies') IS NOT NULL,
                    to_regclass(current_schema() || '.bill_of_material_revisions') IS NOT NULL,
                    to_regclass(current_schema() || '.bill_of_material_revision_lines') IS NOT NULL,
                    to_regclass(current_schema() || '.job_work_order_revisions') IS NOT NULL,
                    to_regclass(current_schema() || '.job_work_order_stage_assignments') IS NOT NULL,
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'job_work_order_bom_stages'
                          AND column_name = 'stable_key'
                    ),
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'material_out_lines'
                          AND column_name = 'stage_assignment_id'
                    ),
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'material_in_consumptions'
                          AND column_name = 'bom_stage_id'
                    ),
                    EXISTS (
                        SELECT 1 FROM stock_groups
                        WHERE name_normalized = 'SEMI-FINISHED GOODS'
                    ),
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'job_work_order_stage_assignments'
                          AND column_name = 'expected_completion_date'
                    ),
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'vouchers'
                          AND column_name = 'audit_identity'
                          AND is_nullable = 'NO'
                    ),
                    to_regclass(current_schema() || '.voucher_audit_revisions') IS NOT NULL,
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'companies'
                          AND column_name = 'stock_frozen_through'
                          AND is_nullable = 'YES'
                    ),
                    to_regclass(current_schema() || '.inventory_inward_lines') IS NOT NULL,
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'stock_movements'
                          AND column_name = 'inventory_inward_line_id'
                    ),
                    EXISTS (
                        SELECT 1 FROM voucher_types
                        WHERE company_id = 1
                          AND system_type_code = 'OPENING_STOCK'
                          AND is_system
                          AND is_active
                    ),
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'vouchers'
                          AND column_name = 'opening_stock_item_id'
                    ),
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'companies'
                          AND column_name = 'allow_negative_stock'
                          AND is_nullable = 'NO'
                    ),
                    to_regclass(current_schema() || '.inventory_posting_sequences') IS NOT NULL,
                    to_regclass(current_schema() || '.inventory_postings') IS NOT NULL,
                    to_regclass(current_schema() || '.inventory_cost_layers') IS NOT NULL,
                    to_regclass(current_schema() || '.inventory_cost_allocations') IS NOT NULL,
                    to_regclass(current_schema() || '.inventory_valuation_positions') IS NOT NULL,
                    to_regclass(current_schema() || '.inventory_valuation_settings') IS NOT NULL,
                    to_regclass(current_schema() || '.inventory_valuation_runs') IS NOT NULL,
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'stock_movements'
                          AND column_name = 'inventory_posting_id'
                          AND is_nullable = 'YES'
                    ),
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'stock_movements'
                          AND column_name = 'movement_line_order'
                          AND is_nullable = 'YES'
                    ),
                    EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'audit_logs'
                          AND column_name = 'correlation_id'
                          AND is_nullable = 'YES'
                    ),
                    EXISTS (
                        SELECT 1 FROM inventory_valuation_settings
                        WHERE company_id = 1
                          AND book_method = 'LegacyPersistedValue'
                          AND lifecycle_state = 'NotInitialized'
                    )
                """, connection);
            await using var reader = await verify.ExecuteReaderAsync();
            Assert.True(await reader.ReadAsync());
            for (var column = 0; column < reader.FieldCount; column++) Assert.True(reader.GetBoolean(column));

            await reader.DisposeAsync();
            await using var hardenedConstraints = new NpgsqlCommand("""
                SELECT COUNT(*)
                FROM pg_constraint
                WHERE connamespace = (SELECT oid FROM pg_namespace WHERE nspname = current_schema())
                  AND conname IN
                  (
                      'fk_bom_revision_line_child_revision_pair',
                      'fk_material_out_stage_assignment_pair',
                      'fk_material_in_fg_stage_assignment_pair',
                      'fk_material_in_consumption_stage_assignment_pair'
                  )
                """, connection);
            Assert.Equal(4L, (long)(await hardenedConstraints.ExecuteScalarAsync() ?? 0L));

            await using var freezeConstraints = new NpgsqlCommand("""
                SELECT COUNT(*)
                FROM pg_constraint
                WHERE connamespace = (SELECT oid FROM pg_namespace WHERE nspname = current_schema())
                  AND conname IN
                  (
                      'ck_stock_movement_kind',
                      'fk_bill_of_material_current_revision_pair'
                  )
                """, connection);
            Assert.Equal(2L, (long)(await freezeConstraints.ExecuteScalarAsync() ?? 0L));

            await using var invalidKind = new NpgsqlCommand("""
                UPDATE stock_movements SET movement_kind = 'Bogus' WHERE false;
                INSERT INTO stock_movements
                    (company_id, financial_year_id, voucher_id, movement_date, stock_item_id, uqc_id,
                     godown_id, quantity_change, rate, value_change, movement_kind, created_at_utc, created_by)
                SELECT 1, 1, 1, DATE '2026-04-01', 1, 1, 1, 1, 0, 0, 'Bogus', NOW(), 'Test'
                WHERE EXISTS (SELECT 1 FROM vouchers WHERE id = 1)
                """, connection);
            var invalidKindError = await Record.ExceptionAsync(() => invalidKind.ExecuteNonQueryAsync());
            if (await ScalarLongAsync(connection, "SELECT COUNT(*) FROM vouchers WHERE id = 1") > 0)
                Assert.IsType<PostgresException>(invalidKindError);

            await using var inwardFixture = new NpgsqlCommand("""
                INSERT INTO stock_groups
                    (company_id, name, name_normalized, alias, root_classification,
                     is_system, is_active, created_at_utc, modified_at_utc,
                     created_by, modified_by, concurrency_token)
                VALUES
                    (1, 'Inward Trigger Group', 'INWARD TRIGGER GROUP', '', 'RawMaterial',
                     false, true, NOW(), NOW(), 'Test', 'Test', md5(random()::text));

                INSERT INTO uqcs
                    (company_id, name, name_normalized, alias, short_name, decimal_places,
                     is_system, is_active, created_at_utc, modified_at_utc,
                     created_by, modified_by, concurrency_token)
                VALUES
                    (1, 'Inward Trigger Units', 'INWARD TRIGGER UNITS', '', 'ITU', 4,
                     false, true, NOW(), NOW(), 'Test', 'Test', md5(random()::text));

                INSERT INTO colours
                    (company_id, name, name_normalized, alias, colour_code,
                     is_system, is_active, created_at_utc, modified_at_utc,
                     created_by, modified_by, concurrency_token)
                VALUES
                    (1, 'Inward Trigger Colour', 'INWARD TRIGGER COLOUR', '', 'ITC',
                     false, true, NOW(), NOW(), 'Test', 'Test', md5(random()::text));

                INSERT INTO sizes
                    (company_id, name, name_normalized, alias, display_order,
                     is_system, is_active, created_at_utc, modified_at_utc,
                     created_by, modified_by, concurrency_token)
                VALUES
                    (1, 'Inward Trigger Size', 'INWARD TRIGGER SIZE', '', 10,
                     false, true, NOW(), NOW(), 'Test', 'Test', md5(random()::text));

                INSERT INTO godowns
                    (company_id, name, name_normalized, alias, address_line1, address_line2,
                     city, state, is_system, is_active, created_at_utc, modified_at_utc,
                     created_by, modified_by, concurrency_token)
                VALUES
                    (1, 'Inward Trigger Godown', 'INWARD TRIGGER GODOWN', '', '', '', '', '',
                     false, true, NOW(), NOW(), 'Test', 'Test', md5(random()::text));

                INSERT INTO stock_items
                    (company_id, name, name_normalized, alias, stock_group_id, uqc_id,
                     tax_mode, hsn_code, is_system, is_active, created_at_utc, modified_at_utc,
                     created_by, modified_by, concurrency_token)
                SELECT 1, 'Inward Trigger Item', 'INWARD TRIGGER ITEM', '', sg.id, u.id,
                       'NotApplicable', '', false, true, NOW(), NOW(), 'Test', 'Test', md5(random()::text)
                FROM (SELECT id FROM stock_groups WHERE name_normalized = 'INWARD TRIGGER GROUP') sg
                CROSS JOIN (SELECT id FROM uqcs WHERE name_normalized = 'INWARD TRIGGER UNITS') u;

                INSERT INTO stock_item_colours (stock_item_id, colour_id)
                SELECT si.id, colour.id
                FROM stock_items si
                CROSS JOIN colours colour
                WHERE si.name_normalized = 'INWARD TRIGGER ITEM'
                  AND colour.name_normalized = 'INWARD TRIGGER COLOUR';

                INSERT INTO stock_item_sizes (stock_item_id, size_id)
                SELECT si.id, size_master.id
                FROM stock_items si
                CROSS JOIN sizes size_master
                WHERE si.name_normalized = 'INWARD TRIGGER ITEM'
                  AND size_master.name_normalized = 'INWARD TRIGGER SIZE';

                INSERT INTO stock_item_variants
                    (company_id, stock_item_id, colour_id, size_id, variant_key, is_active, created_at_utc,
                     modified_at_utc, created_by, modified_by, concurrency_token)
                SELECT 1, si.id, colour.id, size_master.id,
                       'C:' || colour.id || '|S:' || size_master.id,
                       true, NOW(), NOW(), 'Test', 'Test', md5(random()::text)
                FROM stock_items si
                CROSS JOIN colours colour
                CROSS JOIN sizes size_master
                WHERE si.name_normalized = 'INWARD TRIGGER ITEM'
                  AND colour.name_normalized = 'INWARD TRIGGER COLOUR'
                  AND size_master.name_normalized = 'INWARD TRIGGER SIZE';

                INSERT INTO vouchers
                    (company_id, financial_year_id, voucher_type_id, sequence_number,
                     voucher_number, voucher_number_normalized, voucher_date, opening_stock_item_id,
                     status, created_at_utc, modified_at_utc, created_by, modified_by, concurrency_token)
                SELECT 1, 1, vt.id, 900001,
                       'INWARD-TRIGGER-TEST', 'INWARD-TRIGGER-TEST', DATE '2026-04-01', si.id,
                       'Open', NOW(), NOW(), 'Test', 'Test', md5(random()::text)
                FROM voucher_types vt
                CROSS JOIN (SELECT id FROM stock_items WHERE name_normalized = 'INWARD TRIGGER ITEM') si
                WHERE vt.company_id = 1 AND vt.system_type_code = 'OPENING_STOCK';

                INSERT INTO inventory_inward_lines
                    (voucher_id, line_number, stock_item_id, stock_item_variant_id,
                     uqc_id, godown_id, quantity, rate, amount)
                SELECT v.id, 1, si.id, variant.id, si.uqc_id, g.id, 10, 2, 20
                FROM vouchers v
                CROSS JOIN LATERAL
                    (SELECT * FROM stock_items WHERE name_normalized = 'INWARD TRIGGER ITEM') si
                CROSS JOIN LATERAL
                    (SELECT * FROM stock_item_variants WHERE stock_item_id = si.id ORDER BY id LIMIT 1) variant
                CROSS JOIN LATERAL
                    (SELECT * FROM godowns WHERE name_normalized = 'INWARD TRIGGER GODOWN') g
                WHERE v.voucher_number_normalized = 'INWARD-TRIGGER-TEST';
                """, connection);
            await inwardFixture.ExecuteNonQueryAsync();
            Assert.Equal(1L, await ScalarLongAsync(connection,
                "SELECT COUNT(*) FROM stock_items WHERE name_normalized = 'INWARD TRIGGER ITEM'"));
            Assert.Equal(1L, await ScalarLongAsync(connection,
                "SELECT COUNT(*) FROM stock_item_variants WHERE stock_item_id = (SELECT id FROM stock_items WHERE name_normalized = 'INWARD TRIGGER ITEM')"));
            Assert.Equal(1L, await ScalarLongAsync(connection,
                "SELECT COUNT(*) FROM vouchers WHERE voucher_number_normalized = 'INWARD-TRIGGER-TEST'"));
            Assert.Equal(1L, await ScalarLongAsync(connection,
                "SELECT COUNT(*) FROM inventory_inward_lines"));

            await using var invalidOpeningDate = new NpgsqlCommand("""
                UPDATE vouchers
                   SET voucher_date = DATE '2026-04-02'
                 WHERE voucher_number_normalized = 'INWARD-TRIGGER-TEST'
                """, connection);
            var openingDateError = await Assert.ThrowsAsync<PostgresException>(() =>
                invalidOpeningDate.ExecuteNonQueryAsync());
            Assert.Contains("Books Beginning Date", openingDateError.MessageText, StringComparison.Ordinal);

            await using var mismatchedInwardMovement = new NpgsqlCommand("""
                INSERT INTO stock_movements
                    (company_id, financial_year_id, voucher_id, inventory_inward_line_id,
                     stock_item_variant_id, movement_date, stock_item_id, uqc_id, godown_id,
                     quantity_change, rate, value_change, movement_kind, created_at_utc, created_by)
                SELECT 1, 1, line.voucher_id, line.id,
                       line.stock_item_variant_id, DATE '2026-04-02', line.stock_item_id,
                       line.uqc_id, line.godown_id, line.quantity, line.rate, line.amount,
                       'OpeningStockInward', NOW(), 'Test'
                FROM inventory_inward_lines line
                JOIN vouchers v ON v.id = line.voucher_id
                WHERE v.voucher_number_normalized = 'INWARD-TRIGGER-TEST';
                """, connection);
            var mismatchError = await Assert.ThrowsAsync<PostgresException>(() =>
                mismatchedInwardMovement.ExecuteNonQueryAsync());
            Assert.Contains("does not match its source line", mismatchError.MessageText, StringComparison.Ordinal);

            await using var renameUsedColour = new NpgsqlCommand("""
                UPDATE colours
                   SET name = 'Rewritten Colour', name_normalized = 'REWRITTEN COLOUR'
                 WHERE name_normalized = 'INWARD TRIGGER COLOUR'
                """, connection);
            var colourIdentityError = await Assert.ThrowsAsync<PostgresException>(() =>
                renameUsedColour.ExecuteNonQueryAsync());
            Assert.Contains("Used Colour identity is immutable", colourIdentityError.MessageText, StringComparison.Ordinal);

            await using var renameUsedSize = new NpgsqlCommand("""
                UPDATE sizes
                   SET name = 'Rewritten Size', name_normalized = 'REWRITTEN SIZE'
                 WHERE name_normalized = 'INWARD TRIGGER SIZE'
                """, connection);
            var sizeIdentityError = await Assert.ThrowsAsync<PostgresException>(() =>
                renameUsedSize.ExecuteNonQueryAsync());
            Assert.Contains("Used Size identity is immutable", sizeIdentityError.MessageText, StringComparison.Ordinal);

            await using var repurposeUsedVariant = new NpgsqlCommand("""
                UPDATE stock_item_variants
                   SET variant_key = variant_key || '-REWRITTEN'
                 WHERE stock_item_id = (SELECT id FROM stock_items WHERE name_normalized = 'INWARD TRIGGER ITEM')
                """, connection);
            var variantIdentityError = await Assert.ThrowsAsync<PostgresException>(() =>
                repurposeUsedVariant.ExecuteNonQueryAsync());
            Assert.Contains("Used Stock Item Variant identity is immutable", variantIdentityError.MessageText, StringComparison.Ordinal);

            await using var deactivateUsedAttributes = new NpgsqlCommand("""
                UPDATE colours SET is_active = false WHERE name_normalized = 'INWARD TRIGGER COLOUR';
                UPDATE sizes SET is_active = false WHERE name_normalized = 'INWARD TRIGGER SIZE';
                """, connection);
            Assert.Equal(2, await deactivateUsedAttributes.ExecuteNonQueryAsync());
            Assert.Equal(2L, await ScalarLongAsync(connection, """
                SELECT
                    (SELECT COUNT(*) FROM colours WHERE name_normalized = 'INWARD TRIGGER COLOUR' AND NOT is_active)
                  + (SELECT COUNT(*) FROM sizes WHERE name_normalized = 'INWARD TRIGGER SIZE' AND NOT is_active)
                """));

            var options = new DbContextOptionsBuilder<TexTrackDbContext>()
                .UseNpgsql(testBuilder.ConnectionString)
                .Options;
            await using var mappedDb = new TexTrackDbContext(options);
            var criticalTables = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "vouchers", "bill_of_material_revisions", "bill_of_material_revision_lines",
                "job_work_order_bom_stages", "job_work_order_stage_assignments",
                "material_out_lines", "material_in_finished_goods", "material_in_consumptions",
                "inventory_inward_lines", "stock_movements", "voucher_audit_revisions", "companies",
                "inventory_posting_sequences", "inventory_postings", "inventory_cost_layers",
                "inventory_cost_allocations", "inventory_valuation_positions",
                "inventory_valuation_settings", "inventory_valuation_runs", "audit_logs"
            };
            var databaseColumns = new Dictionary<(string Table, string Column), bool>();
            await using (var columns = new NpgsqlCommand("""
                SELECT table_name, column_name, is_nullable = 'YES'
                FROM information_schema.columns
                WHERE table_schema = current_schema()
                """, connection))
            await using (var columnReader = await columns.ExecuteReaderAsync())
            {
                while (await columnReader.ReadAsync())
                    databaseColumns[(columnReader.GetString(0), columnReader.GetString(1))] = columnReader.GetBoolean(2);
            }

            foreach (var entityType in mappedDb.Model.GetEntityTypes())
            {
                var table = entityType.GetTableName();
                if (table is null || !criticalTables.Contains(table)) continue;
                var storeObject = StoreObjectIdentifier.Table(table, entityType.GetSchema());
                foreach (var property in entityType.GetProperties())
                {
                    var column = property.GetColumnName(storeObject);
                    if (column is null) continue;
                    Assert.True(databaseColumns.TryGetValue((table, column), out var nullable),
                        $"EF maps {table}.{column}, but the migration-built PostgreSQL schema does not contain it.");
                    Assert.Equal(property.IsNullable, nullable);
                }
            }
        }
        finally
        {
            await using var drop = new NpgsqlCommand($"DROP SCHEMA IF EXISTS \"{schema}\" CASCADE", admin);
            await drop.ExecuteNonQueryAsync();
        }
    }

    private static async Task<long> ScalarLongAsync(NpgsqlConnection connection, string sql)
    {
        await using var command = new NpgsqlCommand(sql, connection);
        return (long)(await command.ExecuteScalarAsync() ?? 0L);
    }
}
