CREATE TABLE IF NOT EXISTS companies
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    name_normalized varchar(200) NOT NULL,
    code varchar(50) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at_utc timestamp with time zone NOT NULL,
    modified_at_utc timestamp with time zone NOT NULL,
    created_by varchar(100) NOT NULL,
    modified_by varchar(100) NOT NULL,
    concurrency_token varchar(32) NOT NULL,
    CONSTRAINT uq_companies_name_normalized UNIQUE (name_normalized),
    CONSTRAINT uq_companies_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS financial_years
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    name varchar(50) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at_utc timestamp with time zone NOT NULL,
    modified_at_utc timestamp with time zone NOT NULL,
    created_by varchar(100) NOT NULL,
    modified_by varchar(100) NOT NULL,
    concurrency_token varchar(32) NOT NULL,
    CONSTRAINT uq_financial_years_company_name UNIQUE (company_id, name)
);

CREATE TABLE IF NOT EXISTS ledger_groups
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    parent_id bigint NULL REFERENCES ledger_groups(id) ON DELETE RESTRICT,
    name varchar(200) NOT NULL,
    name_normalized varchar(200) NOT NULL,
    alias varchar(200) NOT NULL DEFAULT '',
    root_classification varchar(80) NOT NULL DEFAULT '',
    is_system boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at_utc timestamp with time zone NOT NULL,
    modified_at_utc timestamp with time zone NOT NULL,
    created_by varchar(100) NOT NULL,
    modified_by varchar(100) NOT NULL,
    concurrency_token varchar(32) NOT NULL,
    CONSTRAINT uq_ledger_groups_company_name UNIQUE (company_id, name_normalized)
);
CREATE INDEX IF NOT EXISTS ix_ledger_groups_parent ON ledger_groups(parent_id);

CREATE TABLE IF NOT EXISTS uqcs
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    name varchar(200) NOT NULL,
    name_normalized varchar(200) NOT NULL,
    alias varchar(200) NOT NULL DEFAULT '',
    short_name varchar(20) NOT NULL,
    decimal_places integer NOT NULL DEFAULT 0,
    is_system boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at_utc timestamp with time zone NOT NULL,
    modified_at_utc timestamp with time zone NOT NULL,
    created_by varchar(100) NOT NULL,
    modified_by varchar(100) NOT NULL,
    concurrency_token varchar(32) NOT NULL,
    CONSTRAINT uq_uqcs_company_name UNIQUE (company_id, name_normalized),
    CONSTRAINT ck_uqcs_decimal_places CHECK (decimal_places BETWEEN 0 AND 6)
);

CREATE TABLE IF NOT EXISTS stock_groups
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    parent_id bigint NULL REFERENCES stock_groups(id) ON DELETE RESTRICT,
    name varchar(200) NOT NULL,
    name_normalized varchar(200) NOT NULL,
    alias varchar(200) NOT NULL DEFAULT '',
    root_classification varchar(80) NOT NULL DEFAULT '',
    is_system boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at_utc timestamp with time zone NOT NULL,
    modified_at_utc timestamp with time zone NOT NULL,
    created_by varchar(100) NOT NULL,
    modified_by varchar(100) NOT NULL,
    concurrency_token varchar(32) NOT NULL,
    CONSTRAINT uq_stock_groups_company_name UNIQUE (company_id, name_normalized)
);
CREATE INDEX IF NOT EXISTS ix_stock_groups_parent ON stock_groups(parent_id);

CREATE TABLE IF NOT EXISTS stock_categories
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    name varchar(200) NOT NULL,
    name_normalized varchar(200) NOT NULL,
    alias varchar(200) NOT NULL DEFAULT '',
    is_system boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at_utc timestamp with time zone NOT NULL,
    modified_at_utc timestamp with time zone NOT NULL,
    created_by varchar(100) NOT NULL,
    modified_by varchar(100) NOT NULL,
    concurrency_token varchar(32) NOT NULL,
    CONSTRAINT uq_stock_categories_company_name UNIQUE (company_id, name_normalized)
);

CREATE TABLE IF NOT EXISTS godowns
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    name varchar(200) NOT NULL,
    name_normalized varchar(200) NOT NULL,
    alias varchar(200) NOT NULL DEFAULT '',
    is_system boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at_utc timestamp with time zone NOT NULL,
    modified_at_utc timestamp with time zone NOT NULL,
    created_by varchar(100) NOT NULL,
    modified_by varchar(100) NOT NULL,
    concurrency_token varchar(32) NOT NULL,
    CONSTRAINT uq_godowns_company_name UNIQUE (company_id, name_normalized)
);

CREATE TABLE IF NOT EXISTS colours
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    name varchar(200) NOT NULL,
    name_normalized varchar(200) NOT NULL,
    alias varchar(200) NOT NULL DEFAULT '',
    is_system boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at_utc timestamp with time zone NOT NULL,
    modified_at_utc timestamp with time zone NOT NULL,
    created_by varchar(100) NOT NULL,
    modified_by varchar(100) NOT NULL,
    concurrency_token varchar(32) NOT NULL,
    CONSTRAINT uq_colours_company_name UNIQUE (company_id, name_normalized)
);

CREATE TABLE IF NOT EXISTS sizes
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    name varchar(200) NOT NULL,
    name_normalized varchar(200) NOT NULL,
    alias varchar(200) NOT NULL DEFAULT '',
    is_system boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at_utc timestamp with time zone NOT NULL,
    modified_at_utc timestamp with time zone NOT NULL,
    created_by varchar(100) NOT NULL,
    modified_by varchar(100) NOT NULL,
    concurrency_token varchar(32) NOT NULL,
    CONSTRAINT uq_sizes_company_name UNIQUE (company_id, name_normalized)
);

CREATE TABLE IF NOT EXISTS processes
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    name varchar(200) NOT NULL,
    name_normalized varchar(200) NOT NULL,
    alias varchar(200) NOT NULL DEFAULT '',
    is_system boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at_utc timestamp with time zone NOT NULL,
    modified_at_utc timestamp with time zone NOT NULL,
    created_by varchar(100) NOT NULL,
    modified_by varchar(100) NOT NULL,
    concurrency_token varchar(32) NOT NULL,
    CONSTRAINT uq_processes_company_name UNIQUE (company_id, name_normalized)
);

CREATE TABLE IF NOT EXISTS tax_classifications
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    name varchar(200) NOT NULL,
    name_normalized varchar(200) NOT NULL,
    alias varchar(200) NOT NULL DEFAULT '',
    tax_mode varchar(40) NOT NULL DEFAULT 'NotApplicable',
    is_system boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at_utc timestamp with time zone NOT NULL,
    modified_at_utc timestamp with time zone NOT NULL,
    created_by varchar(100) NOT NULL,
    modified_by varchar(100) NOT NULL,
    concurrency_token varchar(32) NOT NULL,
    CONSTRAINT uq_tax_classifications_company_name UNIQUE (company_id, name_normalized)
);

CREATE TABLE IF NOT EXISTS voucher_types
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    name varchar(200) NOT NULL,
    name_normalized varchar(200) NOT NULL,
    alias varchar(200) NOT NULL DEFAULT '',
    system_type_code varchar(60) NOT NULL,
    nature varchar(100) NOT NULL,
    posting_mode varchar(100) NOT NULL,
    abbreviation varchar(20) NOT NULL DEFAULT '',
    allow_manual_numbering boolean NOT NULL DEFAULT false,
    prefix varchar(30) NOT NULL DEFAULT '',
    starting_number integer NOT NULL DEFAULT 1,
    tally_voucher_type_name varchar(200) NOT NULL DEFAULT '',
    is_system boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at_utc timestamp with time zone NOT NULL,
    modified_at_utc timestamp with time zone NOT NULL,
    created_by varchar(100) NOT NULL,
    modified_by varchar(100) NOT NULL,
    concurrency_token varchar(32) NOT NULL,
    CONSTRAINT uq_voucher_types_company_name UNIQUE (company_id, name_normalized),
    CONSTRAINT uq_voucher_types_company_system_code UNIQUE (company_id, system_type_code)
);

CREATE TABLE IF NOT EXISTS audit_logs
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NULL,
    entity_type varchar(100) NOT NULL,
    entity_id bigint NULL,
    action varchar(50) NOT NULL,
    success boolean NOT NULL,
    description varchar(1000) NOT NULL,
    performed_by varchar(100) NOT NULL,
    performed_at_utc timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_audit_logs_company_time ON audit_logs(company_id, performed_at_utc);

INSERT INTO companies
(id, name, name_normalized, code, is_active, created_at_utc, modified_at_utc, created_by, modified_by, concurrency_token)
VALUES
(1, 'Demo Company', 'DEMO COMPANY', 'DEMO', true, NOW(), NOW(), 'System', 'System', md5(random()::text))
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('companies', 'id'), GREATEST((SELECT MAX(id) FROM companies), 1), true);

INSERT INTO financial_years
(id, company_id, name, start_date, end_date, is_active, created_at_utc, modified_at_utc, created_by, modified_by, concurrency_token)
VALUES
(1, 1, '2026-27', DATE '2026-04-01', DATE '2027-03-31', true, NOW(), NOW(), 'System', 'System', md5(random()::text))
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('financial_years', 'id'), GREATEST((SELECT MAX(id) FROM financial_years), 1), true);

INSERT INTO ledger_groups
(company_id, name, name_normalized, alias, root_classification, is_system, is_active, created_at_utc, modified_at_utc, created_by, modified_by, concurrency_token)
VALUES
(1, 'Capital Account', 'CAPITAL ACCOUNT', '', 'CapitalAccount', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Reserves & Surplus', 'RESERVES & SURPLUS', '', 'ReservesSurplus', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Secured Loans', 'SECURED LOANS', '', 'SecuredLoans', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Unsecured Loans', 'UNSECURED LOANS', '', 'UnsecuredLoans', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Bank Overdraft/OCC', 'BANK OVERDRAFT/OCC', '', 'BankOverdraft', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Sundry Creditors', 'SUNDRY CREDITORS', '', 'SundryCreditors', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Duties & Taxes', 'DUTIES & TAXES', '', 'DutiesTaxes', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Provisions', 'PROVISIONS', '', 'Provisions', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Fixed Assets', 'FIXED ASSETS', '', 'FixedAssets', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Investments', 'INVESTMENTS', '', 'Investments', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Current Assets', 'CURRENT ASSETS', '', 'CurrentAssets', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Stock-in-Hand', 'STOCK-IN-HAND', '', 'StockInHand', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Sundry Debtors', 'SUNDRY DEBTORS', '', 'SundryDebtors', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Cash-in-Hand', 'CASH-IN-HAND', '', 'CashInHand', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Bank Accounts', 'BANK ACCOUNTS', '', 'BankAccounts', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Deposits', 'DEPOSITS', '', 'Deposits', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Loans & Advances', 'LOANS & ADVANCES', '', 'LoansAdvances', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Suspense Account', 'SUSPENSE ACCOUNT', '', 'SuspenseAccount', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Sales Accounts', 'SALES ACCOUNTS', '', 'SalesAccounts', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Purchase Accounts', 'PURCHASE ACCOUNTS', '', 'PurchaseAccounts', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Direct Income', 'DIRECT INCOME', '', 'DirectIncome', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Direct Expenses', 'DIRECT EXPENSES', '', 'DirectExpenses', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Indirect Income', 'INDIRECT INCOME', '', 'IndirectIncome', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Indirect Expenses', 'INDIRECT EXPENSES', '', 'IndirectExpenses', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text))
ON CONFLICT (company_id, name_normalized) DO NOTHING;

INSERT INTO stock_groups
(company_id, name, name_normalized, alias, root_classification, is_system, is_active, created_at_utc, modified_at_utc, created_by, modified_by, concurrency_token)
VALUES
(1, 'Raw Material', 'RAW MATERIAL', 'RM', 'RawMaterial', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Work In Progress', 'WORK IN PROGRESS', 'WIP', 'WorkInProgress', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Finished Goods', 'FINISHED GOODS', 'FG', 'FinishedGoods', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text))
ON CONFLICT (company_id, name_normalized) DO NOTHING;

INSERT INTO uqcs
(company_id, name, name_normalized, alias, short_name, decimal_places, is_system, is_active, created_at_utc, modified_at_utc, created_by, modified_by, concurrency_token)
VALUES
(1, 'Pieces', 'PIECES', '', 'PCS', 2, true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Metres', 'METRES', '', 'MTS', 2, true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Kilograms', 'KILOGRAMS', '', 'KGS', 3, true, true, NOW(), NOW(), 'System', 'System', md5(random()::text))
ON CONFLICT (company_id, name_normalized) DO NOTHING;

INSERT INTO stock_categories
(company_id, name, name_normalized, alias, is_system, is_active, created_at_utc, modified_at_utc, created_by, modified_by, concurrency_token)
VALUES
(1, 'Not Applicable', 'NOT APPLICABLE', '', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text))
ON CONFLICT (company_id, name_normalized) DO NOTHING;

INSERT INTO godowns
(company_id, name, name_normalized, alias, is_system, is_active, created_at_utc, modified_at_utc, created_by, modified_by, concurrency_token)
VALUES
(1, 'Main Godown', 'MAIN GODOWN', 'MAIN', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text))
ON CONFLICT (company_id, name_normalized) DO NOTHING;

INSERT INTO tax_classifications
(company_id, name, name_normalized, alias, tax_mode, is_system, is_active, created_at_utc, modified_at_utc, created_by, modified_by, concurrency_token)
VALUES
(1, 'Not Applicable', 'NOT APPLICABLE', 'NA', 'NotApplicable', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text))
ON CONFLICT (company_id, name_normalized) DO NOTHING;

INSERT INTO voucher_types
(company_id, name, name_normalized, alias, system_type_code, nature, posting_mode, abbreviation, allow_manual_numbering, prefix, starting_number, tally_voucher_type_name, is_system, is_active, created_at_utc, modified_at_utc, created_by, modified_by, concurrency_token)
VALUES
(1, 'Sales', 'SALES', '', 'SALES', 'Accounting + Inventory', 'Enabled later', 'SAL', false, '', 1, 'Sales', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Purchase', 'PURCHASE', '', 'PURCHASE', 'Accounting + Inventory', 'Enabled later', 'PUR', false, '', 1, 'Purchase', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Sales Return', 'SALES RETURN', '', 'SALES_RETURN', 'Accounting + Inventory', 'Enabled later', 'SR', false, '', 1, 'Credit Note', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Purchase Return', 'PURCHASE RETURN', '', 'PURCHASE_RETURN', 'Accounting + Inventory', 'Enabled later', 'PR', false, '', 1, 'Debit Note', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Job Work Out Order', 'JOB WORK OUT ORDER', '', 'JOB_WORK_OUT_ORDER', 'Planning', 'No financial posting', 'JWO', false, '', 1, 'Job Work Out Order', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Job Work In Order', 'JOB WORK IN ORDER', '', 'JOB_WORK_IN_ORDER', 'Planning', 'No financial posting', 'JWI', false, '', 1, 'Job Work In Order', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Material Out', 'MATERIAL OUT', '', 'MATERIAL_OUT', 'Inventory Movement', 'Enabled later', 'MO', false, '', 1, 'Material Out', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Material In', 'MATERIAL IN', '', 'MATERIAL_IN', 'Inventory Transformation', 'Enabled later', 'MI', false, '', 1, 'Material In', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Payment', 'PAYMENT', '', 'PAYMENT', 'Accounting', 'Enabled later', 'PAY', false, '', 1, 'Payment', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Receipt', 'RECEIPT', '', 'RECEIPT', 'Accounting', 'Enabled later', 'RCT', false, '', 1, 'Receipt', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Contra', 'CONTRA', '', 'CONTRA', 'Accounting', 'Enabled later', 'CON', false, '', 1, 'Contra', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Journal', 'JOURNAL', '', 'JOURNAL', 'Accounting', 'Enabled later', 'JRN', false, '', 1, 'Journal', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Stock Journal', 'STOCK JOURNAL', '', 'STOCK_JOURNAL', 'Inventory', 'Enabled later', 'SJ', false, '', 1, 'Stock Journal', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Purchase Order', 'PURCHASE ORDER', '', 'PURCHASE_ORDER', 'Planning', 'No financial posting', 'PO', false, '', 1, 'Purchase Order', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Sales Order', 'SALES ORDER', '', 'SALES_ORDER', 'Planning', 'No financial posting', 'SO', false, '', 1, 'Sales Order', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)),
(1, 'Master Job Order', 'MASTER JOB ORDER', '', 'MASTER_JOB_ORDER', 'Planning', 'No financial posting', 'MJO', false, '', 1, 'Master Job Order', true, true, NOW(), NOW(), 'System', 'System', md5(random()::text))
ON CONFLICT (company_id, name_normalized) DO NOTHING;
