CREATE TABLE IF NOT EXISTS ledgers
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    ledger_group_id bigint NOT NULL REFERENCES ledger_groups(id) ON DELETE RESTRICT,
    name varchar(200) NOT NULL,
    name_normalized varchar(200) NOT NULL,
    alias varchar(200) NOT NULL DEFAULT '',
    mailing_name varchar(200) NOT NULL DEFAULT '',
    address_line1 varchar(250) NOT NULL DEFAULT '',
    address_line2 varchar(250) NOT NULL DEFAULT '',
    city varchar(100) NOT NULL DEFAULT '',
    state varchar(100) NOT NULL DEFAULT '',
    country varchar(100) NOT NULL DEFAULT 'India',
    pin_code varchar(20) NOT NULL DEFAULT '',
    contact_person varchar(150) NOT NULL DEFAULT '',
    phone varchar(50) NOT NULL DEFAULT '',
    mobile varchar(50) NOT NULL DEFAULT '',
    email varchar(200) NOT NULL DEFAULT '',
    gst_registration_type varchar(50) NOT NULL DEFAULT 'Unregistered',
    gstin varchar(15) NOT NULL DEFAULT '',
    pan varchar(10) NOT NULL DEFAULT '',
    maintain_bill_wise boolean NOT NULL DEFAULT false,
    credit_period_days integer NOT NULL DEFAULT 0,
    credit_limit numeric(19,4) NOT NULL DEFAULT 0,
    opening_balance numeric(19,4) NOT NULL DEFAULT 0,
    opening_balance_type varchar(2) NOT NULL DEFAULT 'Dr',
    bank_account_number varchar(50) NOT NULL DEFAULT '',
    bank_ifsc varchar(20) NOT NULL DEFAULT '',
    bank_name varchar(150) NOT NULL DEFAULT '',
    bank_branch varchar(150) NOT NULL DEFAULT '',
    is_system boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at_utc timestamp with time zone NOT NULL,
    modified_at_utc timestamp with time zone NOT NULL,
    created_by varchar(100) NOT NULL,
    modified_by varchar(100) NOT NULL,
    concurrency_token varchar(32) NOT NULL,
    CONSTRAINT uq_ledgers_company_name UNIQUE (company_id, name_normalized),
    CONSTRAINT ck_ledgers_opening_balance CHECK (opening_balance >= 0),
    CONSTRAINT ck_ledgers_opening_balance_type CHECK (opening_balance_type IN ('Dr', 'Cr')),
    CONSTRAINT ck_ledgers_credit_period CHECK (credit_period_days BETWEEN 0 AND 3650),
    CONSTRAINT ck_ledgers_credit_limit CHECK (credit_limit >= 0)
);

CREATE INDEX IF NOT EXISTS ix_ledgers_company_group ON ledgers(company_id, ledger_group_id);
CREATE INDEX IF NOT EXISTS ix_ledgers_company_gstin ON ledgers(company_id, gstin);

INSERT INTO ledgers
(
    company_id, ledger_group_id, name, name_normalized, alias, mailing_name,
    country, gst_registration_type, opening_balance_type,
    is_system, is_active, created_at_utc, modified_at_utc,
    created_by, modified_by, concurrency_token
)
SELECT
    c.id, lg.id, 'Cash', 'CASH', '', 'Cash',
    'India', 'Unregistered', 'Dr',
    true, true, NOW(), NOW(), 'System', 'System', md5(random()::text)
FROM companies c
JOIN ledger_groups lg
  ON lg.company_id = c.id
 AND lg.root_classification = 'CashInHand'
 AND lg.is_system = true
ON CONFLICT (company_id, name_normalized) DO NOTHING;
