-- TexTrack ERP Build 2.10
-- Persist the ordered Nature of Process allocations entered for each JWO finished-good line.
-- Forward-only and additive: existing JWO, Material Out, Material In and stock records are unchanged.

CREATE TABLE IF NOT EXISTS job_work_order_processes
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finished_good_id bigint NOT NULL REFERENCES job_work_order_finished_goods(id) ON DELETE CASCADE,
    process_id bigint NOT NULL REFERENCES processes(id) ON DELETE RESTRICT,
    expected_rate numeric(19,4) NOT NULL DEFAULT 0,
    rate_basis varchar(50) NOT NULL DEFAULT 'Per Quantity',
    CONSTRAINT ck_jwo_process_expected_rate_nonnegative CHECK (expected_rate >= 0),
    CONSTRAINT ck_jwo_process_rate_basis_nonblank CHECK (btrim(rate_basis) <> ''),
    CONSTRAINT uq_jwo_process_finished_good_process UNIQUE (finished_good_id, process_id)
);

CREATE INDEX IF NOT EXISTS ix_jwo_process_process_finished_good
    ON job_work_order_processes(process_id, finished_good_id);