-- TexTrack ERP Build 2.11
-- Master Job Order planning, JWO parent linkage and backward-compatible multi-colour design grouping.

ALTER TABLE vouchers
    ADD COLUMN IF NOT EXISTS master_job_order_id bigint NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_vouchers_master_job_order') THEN
        ALTER TABLE vouchers
            ADD CONSTRAINT fk_vouchers_master_job_order
            FOREIGN KEY (master_job_order_id) REFERENCES vouchers(id) ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_vouchers_master_job_order
    ON vouchers(master_job_order_id) WHERE master_job_order_id IS NOT NULL;

ALTER TABLE job_work_order_finished_goods
    ADD COLUMN IF NOT EXISTS design_group_key varchar(64);

UPDATE job_work_order_finished_goods
SET design_group_key = 'LEGACY-' || id::text
WHERE design_group_key IS NULL OR btrim(design_group_key) = '';

ALTER TABLE job_work_order_finished_goods
    ALTER COLUMN design_group_key SET NOT NULL;

CREATE INDEX IF NOT EXISTS ix_jwo_finished_goods_design_group
    ON job_work_order_finished_goods(voucher_id, design_group_key, line_number);

CREATE TABLE IF NOT EXISTS master_job_order_finished_goods
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id bigint NOT NULL REFERENCES vouchers(id) ON DELETE CASCADE,
    line_number integer NOT NULL,
    stock_item_id bigint NOT NULL REFERENCES stock_items(id) ON DELETE RESTRICT,
    ordered_quantity numeric(19,4) NOT NULL DEFAULT 0,
    CONSTRAINT ck_mjo_finished_good_quantity_positive CHECK (ordered_quantity > 0),
    CONSTRAINT uq_mjo_finished_good_line UNIQUE (voucher_id, line_number),
    CONSTRAINT uq_mjo_finished_good_item UNIQUE (voucher_id, stock_item_id)
);

CREATE INDEX IF NOT EXISTS ix_mjo_finished_good_item
    ON master_job_order_finished_goods(stock_item_id, voucher_id);

CREATE TABLE IF NOT EXISTS master_job_order_allocations
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finished_good_id bigint NOT NULL REFERENCES master_job_order_finished_goods(id) ON DELETE CASCADE,
    stock_item_variant_id bigint NOT NULL REFERENCES stock_item_variants(id) ON DELETE RESTRICT,
    colour_id bigint NULL REFERENCES colours(id) ON DELETE RESTRICT,
    size_id bigint NULL REFERENCES sizes(id) ON DELETE RESTRICT,
    quantity numeric(19,4) NOT NULL DEFAULT 0,
    CONSTRAINT ck_mjo_allocation_quantity_positive CHECK (quantity > 0),
    CONSTRAINT uq_mjo_finished_good_variant UNIQUE (finished_good_id, stock_item_variant_id)
);

CREATE INDEX IF NOT EXISTS ix_mjo_allocation_variant
    ON master_job_order_allocations(stock_item_variant_id, finished_good_id);

ALTER TABLE job_work_order_size_allocations
    ADD COLUMN IF NOT EXISTS master_job_order_allocation_id bigint NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_jwo_size_mjo_allocation') THEN
        ALTER TABLE job_work_order_size_allocations
            ADD CONSTRAINT fk_jwo_size_mjo_allocation
            FOREIGN KEY (master_job_order_allocation_id) REFERENCES master_job_order_allocations(id) ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_jwo_size_mjo_allocation
    ON job_work_order_size_allocations(master_job_order_allocation_id)
    WHERE master_job_order_allocation_id IS NOT NULL;
