CREATE TABLE application_users
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name varchar(200) NOT NULL,
    user_name_normalized varchar(200) NOT NULL,
    display_name varchar(200) NOT NULL,
    password_hash varchar(500) NOT NULL,
    security_stamp varchar(32) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    failed_login_count integer NOT NULL DEFAULT 0,
    lockout_end_utc timestamp with time zone NULL,
    last_login_at_utc timestamp with time zone NULL,
    created_at_utc timestamp with time zone NOT NULL,
    modified_at_utc timestamp with time zone NOT NULL,
    CONSTRAINT uq_application_users_name UNIQUE (user_name_normalized),
    CONSTRAINT ck_application_users_failed_login_count CHECK (failed_login_count >= 0)
);

CREATE TABLE security_roles
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(40) NOT NULL,
    name varchar(100) NOT NULL,
    is_system boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_security_roles_code UNIQUE (code)
);

CREATE TABLE application_user_roles
(
    user_id bigint NOT NULL REFERENCES application_users(id) ON DELETE CASCADE,
    role_id bigint NOT NULL REFERENCES security_roles(id) ON DELETE RESTRICT,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE application_user_companies
(
    user_id bigint NOT NULL REFERENCES application_users(id) ON DELETE CASCADE,
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    is_default boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    PRIMARY KEY (user_id, company_id)
);

CREATE INDEX ix_application_user_companies_company_active
    ON application_user_companies(company_id, is_active);
CREATE UNIQUE INDEX uq_application_user_companies_one_default
    ON application_user_companies(user_id) WHERE is_default;

INSERT INTO security_roles(code, name, is_system) VALUES
    ('Developer', 'Developer', true),
    ('Administrator', 'Administrator', true),
    ('Owner', 'Owner', true),
    ('Manager', 'Manager', true),
    ('Operator', 'Operator', true),
    ('Viewer', 'Viewer', true)
ON CONFLICT (code) DO NOTHING;
