-- Immutable BOM revisions and persistent JWO revision/assignment history.

CREATE TABLE bill_of_material_revisions
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_id bigint NOT NULL REFERENCES bill_of_materials(id) ON DELETE RESTRICT,
    revision_number integer NOT NULL CHECK (revision_number > 0),
    stock_item_id bigint NOT NULL REFERENCES stock_items(id) ON DELETE RESTRICT,
    name varchar(200) NOT NULL,
    output_quantity numeric(19,4) NOT NULL CHECK (output_quantity > 0),
    content_hash varchar(64) NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'Active',
    change_reason varchar(500) NOT NULL DEFAULT '',
    created_at_utc timestamptz NOT NULL DEFAULT NOW(),
    created_by varchar(200) NOT NULL DEFAULT 'Migration',
    CONSTRAINT uq_bom_revision_number UNIQUE (bom_id, revision_number)
);
CREATE INDEX ix_bom_revision_content ON bill_of_material_revisions(bom_id, content_hash);

CREATE TABLE bill_of_material_revision_lines
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_revision_id bigint NOT NULL REFERENCES bill_of_material_revisions(id) ON DELETE CASCADE,
    line_number integer NOT NULL CHECK (line_number > 0),
    component_stock_item_id bigint NOT NULL REFERENCES stock_items(id) ON DELETE RESTRICT,
    component_variant_id bigint NULL REFERENCES stock_item_variants(id) ON DELETE RESTRICT,
    uqc_id bigint NOT NULL REFERENCES uqcs(id) ON DELETE RESTRICT,
    required_quantity numeric(19,4) NOT NULL CHECK (required_quantity > 0),
    child_bom_id bigint NULL REFERENCES bill_of_materials(id) ON DELETE RESTRICT,
    child_bom_revision_id bigint NULL REFERENCES bill_of_material_revisions(id) ON DELETE RESTRICT,
    process_id bigint NULL REFERENCES processes(id) ON DELETE RESTRICT,
    notes varchar(500) NOT NULL DEFAULT '',
    CONSTRAINT uq_bom_revision_line UNIQUE (bom_revision_id, line_number),
    CONSTRAINT ck_child_revision_pair CHECK
    (
        (child_bom_id IS NULL AND child_bom_revision_id IS NULL) OR
        (child_bom_id IS NOT NULL AND child_bom_revision_id IS NOT NULL)
    )
);

INSERT INTO bill_of_material_revisions
    (bom_id, revision_number, stock_item_id, name, output_quantity, content_hash,
     status, change_reason, created_at_utc, created_by)
SELECT b.id,
       GREATEST(1, b.version_number),
       b.stock_item_id,
       b.name,
       b.output_quantity,
       md5(concat_ws('|', b.id, b.stock_item_id, b.name_normalized, b.output_quantity,
           COALESCE((SELECT string_agg(concat_ws(':', l.line_number, l.component_stock_item_id,
               COALESCE(l.component_variant_id, 0), l.uqc_id, l.required_quantity,
               COALESCE(l.child_bom_id, 0), COALESCE(l.process_id, 0), COALESCE(l.notes, '')), '|'
               ORDER BY l.line_number)
             FROM bill_of_material_lines l WHERE l.bom_id = b.id), ''))),
       CASE WHEN b.is_active THEN 'Active' ELSE 'Inactive' END,
       'Initial immutable revision backfill',
       COALESCE(b.modified_at_utc, b.created_at_utc, NOW()),
       COALESCE(NULLIF(b.modified_by, ''), NULLIF(b.created_by, ''), 'Migration')
FROM bill_of_materials b;

INSERT INTO bill_of_material_revision_lines
    (bom_revision_id, line_number, component_stock_item_id, component_variant_id,
     uqc_id, required_quantity, child_bom_id, child_bom_revision_id, process_id, notes)
SELECT parent_revision.id,
       l.line_number,
       l.component_stock_item_id,
       l.component_variant_id,
       l.uqc_id,
       l.required_quantity,
       l.child_bom_id,
       child_revision.id,
       l.process_id,
       COALESCE(l.notes, '')
FROM bill_of_material_lines l
JOIN bill_of_material_revisions parent_revision ON parent_revision.bom_id = l.bom_id
LEFT JOIN bill_of_material_revisions child_revision ON child_revision.bom_id = l.child_bom_id;

ALTER TABLE bill_of_materials ADD COLUMN current_revision_id bigint NULL;
UPDATE bill_of_materials b
SET current_revision_id = r.id,
    version_number = r.revision_number
FROM bill_of_material_revisions r
WHERE r.bom_id = b.id;
ALTER TABLE bill_of_materials
    ADD CONSTRAINT fk_bill_of_material_current_revision
    FOREIGN KEY (current_revision_id) REFERENCES bill_of_material_revisions(id) ON DELETE RESTRICT;
CREATE INDEX ix_bill_of_materials_current_revision_id ON bill_of_materials(current_revision_id);

ALTER TABLE job_work_order_bom_stages
    ADD COLUMN source_bom_revision_id bigint NULL,
    ADD COLUMN stable_key uuid NOT NULL DEFAULT gen_random_uuid();
UPDATE job_work_order_bom_stages s
SET source_bom_revision_id = r.id
FROM bill_of_material_revisions r
WHERE r.bom_id = s.source_bom_id
  AND r.revision_number = COALESCE(s.source_bom_version, r.revision_number);
ALTER TABLE job_work_order_bom_stages
    ADD CONSTRAINT fk_jwo_stage_source_bom_revision
    FOREIGN KEY (source_bom_revision_id) REFERENCES bill_of_material_revisions(id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX ux_jwo_stage_stable_key ON job_work_order_bom_stages(stable_key);
CREATE INDEX ix_jwo_stage_source_bom_revision ON job_work_order_bom_stages(source_bom_revision_id);

CREATE TABLE job_work_order_revisions
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id bigint NOT NULL REFERENCES vouchers(id) ON DELETE RESTRICT,
    revision_number integer NOT NULL CHECK (revision_number > 0),
    content_hash varchar(64) NOT NULL,
    snapshot_json jsonb NOT NULL,
    change_reason varchar(500) NOT NULL DEFAULT '',
    is_current boolean NOT NULL DEFAULT true,
    created_at_utc timestamptz NOT NULL DEFAULT NOW(),
    created_by varchar(200) NOT NULL DEFAULT 'Migration',
    CONSTRAINT uq_jwo_revision_number UNIQUE (voucher_id, revision_number)
);
CREATE INDEX ix_jwo_revision_content ON job_work_order_revisions(voucher_id, content_hash);
CREATE UNIQUE INDEX ux_jwo_one_current_revision
    ON job_work_order_revisions(voucher_id) WHERE is_current;

INSERT INTO job_work_order_revisions
    (voucher_id, revision_number, content_hash, snapshot_json, change_reason, is_current, created_at_utc, created_by)
SELECT v.id,
       1,
       md5(concat_ws('|', v.id, v.voucher_number, v.voucher_date, v.batch, COALESCE(v.party_ledger_id, 0),
           COALESCE((SELECT string_agg(concat_ws(':', s.id, s.stage_path, COALESCE(s.source_bom_id, 0),
               COALESCE(s.source_bom_version, 0), COALESCE(s.assigned_job_worker_id, 0)), '|'
               ORDER BY s.stage_number)
             FROM job_work_order_bom_stages s WHERE s.voucher_id = v.id), ''))),
       jsonb_build_object(
           'voucherId', v.id,
           'voucherNumber', v.voucher_number,
           'voucherDate', v.voucher_date,
           'batch', v.batch,
           'partyLedgerId', v.party_ledger_id,
           'migrationSnapshot', true),
       'Initial JWO revision backfill',
       true,
       COALESCE(v.modified_at_utc, v.created_at_utc, NOW()),
       COALESCE(NULLIF(v.modified_by, ''), NULLIF(v.created_by, ''), 'Migration')
FROM vouchers v
JOIN voucher_types vt ON vt.id = v.voucher_type_id
LEFT JOIN voucher_types parent_vt ON parent_vt.id = vt.parent_voucher_type_id
WHERE vt.system_type_code = 'JOB_WORK_OUT_ORDER'
   OR parent_vt.system_type_code = 'JOB_WORK_OUT_ORDER';

CREATE TABLE job_work_order_stage_assignments
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_stage_id bigint NOT NULL REFERENCES job_work_order_bom_stages(id) ON DELETE RESTRICT,
    assignment_version integer NOT NULL CHECK (assignment_version > 0),
    job_worker_id bigint NULL REFERENCES ledgers(id) ON DELETE RESTRICT,
    status varchar(30) NOT NULL DEFAULT 'Active',
    reason varchar(500) NOT NULL DEFAULT '',
    valid_from_utc timestamptz NOT NULL DEFAULT NOW(),
    valid_to_utc timestamptz NULL,
    created_by varchar(200) NOT NULL DEFAULT 'Migration',
    CONSTRAINT uq_jwo_stage_assignment_version UNIQUE (bom_stage_id, assignment_version)
);
CREATE UNIQUE INDEX ux_jwo_stage_one_active_assignment
    ON job_work_order_stage_assignments(bom_stage_id) WHERE status = 'Active';

INSERT INTO job_work_order_stage_assignments
    (bom_stage_id, assignment_version, job_worker_id, status, reason, valid_from_utc, created_by)
SELECT s.id, 1, s.assigned_job_worker_id, 'Active', 'Initial assignment backfill',
       COALESCE(v.modified_at_utc, v.created_at_utc, NOW()),
       COALESCE(NULLIF(v.modified_by, ''), NULLIF(v.created_by, ''), 'Migration')
FROM job_work_order_bom_stages s
JOIN vouchers v ON v.id = s.voucher_id;
